title: iameyad # The title of the blog
author: Eyad Hasan # Your name 
email: me@iameyad.dev # your email shown in the footer
url: https://iameyad.dev # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Personal Blog.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "/assets/pfp.jpg" # avatar in about page
  about_you: DevOps Engineer. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: iameyad
    github:  iameyad
    #rss: RSS
    # dribbble: 
    #facebook: 
    # flickr:   
    # instagram: 
    linkedin: iameyad
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
#theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
